### ISSUE TITLE
角色

### ISSUE THREAD

**Issue by cuitaocrazy** [cuitaocrazy/ws-gateway#3]
资源应有四类
1. 可以不做认证的资源
2. 用户自己的资源，这些资源应只做认证，不做授权
3. 管理员给所有用户的资源，应所有用户可默认拥有, 不必再次为用户分配角色
4. 管理者分配给某些用户的资源，这应是普通角色的功能

目前只做到了1,2,4，没有考虑3的情况, 因为3这种情况只会出现一些业务时遇到，这会对以后带来麻烦
e.g:
每个员工都可查看公司通讯录
A是刚入职新员工
A应有能力自己去查看通讯录
但是现在他需要管理员给他分配角色才可以

**Comment by lirenhao** [comment]
关闭任务，前端在角色中以“default”角色展示
